// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64) && linux

package bpfgen

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// LoadHttpTrace returns the embedded CollectionSpec for HttpTrace.
func LoadHttpTrace() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_HttpTraceBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load HttpTrace: %w", err)
	}

	return spec, err
}

// LoadHttpTraceObjects loads HttpTrace and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*HttpTraceObjects
//	*HttpTracePrograms
//	*HttpTraceMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadHttpTraceObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadHttpTrace()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// HttpTraceSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type HttpTraceSpecs struct {
	HttpTraceProgramSpecs
	HttpTraceMapSpecs
	HttpTraceVariableSpecs
}

// HttpTraceProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type HttpTraceProgramSpecs struct {
	KprobeSockRecvmsg              *ebpf.ProgramSpec `ebpf:"kprobe_sock_recvmsg"`
	KprobeSockSendmsg              *ebpf.ProgramSpec `ebpf:"kprobe_sock_sendmsg"`
	KprobeTcpClose                 *ebpf.ProgramSpec `ebpf:"kprobe_tcp_close"`
	KprobeTcpRecvmsg               *ebpf.ProgramSpec `ebpf:"kprobe_tcp_recvmsg"`
	KprobeTcpSendmsg               *ebpf.ProgramSpec `ebpf:"kprobe_tcp_sendmsg"`
	KprobeTcpV4Connect             *ebpf.ProgramSpec `ebpf:"kprobe_tcp_v4_connect"`
	KprobeTcpV6Connect             *ebpf.ProgramSpec `ebpf:"kprobe_tcp_v6_connect"`
	KretprobeInetCskAccept         *ebpf.ProgramSpec `ebpf:"kretprobe_inet_csk_accept"`
	KretprobeSockRecvmsg           *ebpf.ProgramSpec `ebpf:"kretprobe_sock_recvmsg"`
	KretprobeTcpRecvmsg            *ebpf.ProgramSpec `ebpf:"kretprobe_tcp_recvmsg"`
	KretprobeTcpV4Connect          *ebpf.ProgramSpec `ebpf:"kretprobe_tcp_v4_connect"`
	KretprobeTcpV6Connect          *ebpf.ProgramSpec `ebpf:"kretprobe_tcp_v6_connect"`
	TracepointSockInetSockSetState *ebpf.ProgramSpec `ebpf:"tracepoint_sock_inet_sock_set_state"`
	TracepointSysEnterRead         *ebpf.ProgramSpec `ebpf:"tracepoint_sys_enter_read"`
	TracepointSysEnterReadv        *ebpf.ProgramSpec `ebpf:"tracepoint_sys_enter_readv"`
	TracepointSysEnterRecvfrom     *ebpf.ProgramSpec `ebpf:"tracepoint_sys_enter_recvfrom"`
	TracepointSysEnterRecvmsg      *ebpf.ProgramSpec `ebpf:"tracepoint_sys_enter_recvmsg"`
	TracepointSysEnterSendmsg      *ebpf.ProgramSpec `ebpf:"tracepoint_sys_enter_sendmsg"`
	TracepointSysEnterSendto       *ebpf.ProgramSpec `ebpf:"tracepoint_sys_enter_sendto"`
	TracepointSysEnterWrite        *ebpf.ProgramSpec `ebpf:"tracepoint_sys_enter_write"`
	TracepointSysEnterWritev       *ebpf.ProgramSpec `ebpf:"tracepoint_sys_enter_writev"`
}

// HttpTraceMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type HttpTraceMapSpecs struct {
	ConnectArgsMap *ebpf.MapSpec `ebpf:"connect_args_map"`
	Events         *ebpf.MapSpec `ebpf:"events"`
	FilterMap      *ebpf.MapSpec `ebpf:"filter_map"`
	FlowMap        *ebpf.MapSpec `ebpf:"flow_map"`
	KernelStatsMap *ebpf.MapSpec `ebpf:"kernel_stats_map"`
	RecvArgsMap    *ebpf.MapSpec `ebpf:"recv_args_map"`
	RecvFdMap      *ebpf.MapSpec `ebpf:"recv_fd_map"`
	ScratchHeap    *ebpf.MapSpec `ebpf:"scratch_heap"`
	SendFdMap      *ebpf.MapSpec `ebpf:"send_fd_map"`
	SendGuardMap   *ebpf.MapSpec `ebpf:"send_guard_map"`
	SendScratchMap *ebpf.MapSpec `ebpf:"send_scratch_map"`
	TupleCache     *ebpf.MapSpec `ebpf:"tuple_cache"`
}

// HttpTraceVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type HttpTraceVariableSpecs struct {
}

// HttpTraceObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadHttpTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type HttpTraceObjects struct {
	HttpTracePrograms
	HttpTraceMaps
	HttpTraceVariables
}

func (o *HttpTraceObjects) Close() error {
	return _HttpTraceClose(
		&o.HttpTracePrograms,
		&o.HttpTraceMaps,
	)
}

// HttpTraceMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadHttpTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type HttpTraceMaps struct {
	ConnectArgsMap *ebpf.Map `ebpf:"connect_args_map"`
	Events         *ebpf.Map `ebpf:"events"`
	FilterMap      *ebpf.Map `ebpf:"filter_map"`
	FlowMap        *ebpf.Map `ebpf:"flow_map"`
	KernelStatsMap *ebpf.Map `ebpf:"kernel_stats_map"`
	RecvArgsMap    *ebpf.Map `ebpf:"recv_args_map"`
	RecvFdMap      *ebpf.Map `ebpf:"recv_fd_map"`
	ScratchHeap    *ebpf.Map `ebpf:"scratch_heap"`
	SendFdMap      *ebpf.Map `ebpf:"send_fd_map"`
	SendGuardMap   *ebpf.Map `ebpf:"send_guard_map"`
	SendScratchMap *ebpf.Map `ebpf:"send_scratch_map"`
	TupleCache     *ebpf.Map `ebpf:"tuple_cache"`
}

func (m *HttpTraceMaps) Close() error {
	return _HttpTraceClose(
		m.ConnectArgsMap,
		m.Events,
		m.FilterMap,
		m.FlowMap,
		m.KernelStatsMap,
		m.RecvArgsMap,
		m.RecvFdMap,
		m.ScratchHeap,
		m.SendFdMap,
		m.SendGuardMap,
		m.SendScratchMap,
		m.TupleCache,
	)
}

// HttpTraceVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadHttpTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type HttpTraceVariables struct {
}

// HttpTracePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadHttpTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type HttpTracePrograms struct {
	KprobeSockRecvmsg              *ebpf.Program `ebpf:"kprobe_sock_recvmsg"`
	KprobeSockSendmsg              *ebpf.Program `ebpf:"kprobe_sock_sendmsg"`
	KprobeTcpClose                 *ebpf.Program `ebpf:"kprobe_tcp_close"`
	KprobeTcpRecvmsg               *ebpf.Program `ebpf:"kprobe_tcp_recvmsg"`
	KprobeTcpSendmsg               *ebpf.Program `ebpf:"kprobe_tcp_sendmsg"`
	KprobeTcpV4Connect             *ebpf.Program `ebpf:"kprobe_tcp_v4_connect"`
	KprobeTcpV6Connect             *ebpf.Program `ebpf:"kprobe_tcp_v6_connect"`
	KretprobeInetCskAccept         *ebpf.Program `ebpf:"kretprobe_inet_csk_accept"`
	KretprobeSockRecvmsg           *ebpf.Program `ebpf:"kretprobe_sock_recvmsg"`
	KretprobeTcpRecvmsg            *ebpf.Program `ebpf:"kretprobe_tcp_recvmsg"`
	KretprobeTcpV4Connect          *ebpf.Program `ebpf:"kretprobe_tcp_v4_connect"`
	KretprobeTcpV6Connect          *ebpf.Program `ebpf:"kretprobe_tcp_v6_connect"`
	TracepointSockInetSockSetState *ebpf.Program `ebpf:"tracepoint_sock_inet_sock_set_state"`
	TracepointSysEnterRead         *ebpf.Program `ebpf:"tracepoint_sys_enter_read"`
	TracepointSysEnterReadv        *ebpf.Program `ebpf:"tracepoint_sys_enter_readv"`
	TracepointSysEnterRecvfrom     *ebpf.Program `ebpf:"tracepoint_sys_enter_recvfrom"`
	TracepointSysEnterRecvmsg      *ebpf.Program `ebpf:"tracepoint_sys_enter_recvmsg"`
	TracepointSysEnterSendmsg      *ebpf.Program `ebpf:"tracepoint_sys_enter_sendmsg"`
	TracepointSysEnterSendto       *ebpf.Program `ebpf:"tracepoint_sys_enter_sendto"`
	TracepointSysEnterWrite        *ebpf.Program `ebpf:"tracepoint_sys_enter_write"`
	TracepointSysEnterWritev       *ebpf.Program `ebpf:"tracepoint_sys_enter_writev"`
}

func (p *HttpTracePrograms) Close() error {
	return _HttpTraceClose(
		p.KprobeSockRecvmsg,
		p.KprobeSockSendmsg,
		p.KprobeTcpClose,
		p.KprobeTcpRecvmsg,
		p.KprobeTcpSendmsg,
		p.KprobeTcpV4Connect,
		p.KprobeTcpV6Connect,
		p.KretprobeInetCskAccept,
		p.KretprobeSockRecvmsg,
		p.KretprobeTcpRecvmsg,
		p.KretprobeTcpV4Connect,
		p.KretprobeTcpV6Connect,
		p.TracepointSockInetSockSetState,
		p.TracepointSysEnterRead,
		p.TracepointSysEnterReadv,
		p.TracepointSysEnterRecvfrom,
		p.TracepointSysEnterRecvmsg,
		p.TracepointSysEnterSendmsg,
		p.TracepointSysEnterSendto,
		p.TracepointSysEnterWrite,
		p.TracepointSysEnterWritev,
	)
}

func _HttpTraceClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed httptrace_x86_bpfel.o
var _HttpTraceBytes []byte
