// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64) && linux

package bpfgen

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// LoadTlsTraceLegacy returns the embedded CollectionSpec for TlsTraceLegacy.
func LoadTlsTraceLegacy() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TlsTraceLegacyBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load TlsTraceLegacy: %w", err)
	}

	return spec, err
}

// LoadTlsTraceLegacyObjects loads TlsTraceLegacy and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*TlsTraceLegacyObjects
//	*TlsTraceLegacyPrograms
//	*TlsTraceLegacyMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadTlsTraceLegacyObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadTlsTraceLegacy()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// TlsTraceLegacySpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TlsTraceLegacySpecs struct {
	TlsTraceLegacyProgramSpecs
	TlsTraceLegacyMapSpecs
	TlsTraceLegacyVariableSpecs
}

// TlsTraceLegacyProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TlsTraceLegacyProgramSpecs struct {
	UprobeSslClear          *ebpf.ProgramSpec `ebpf:"uprobe_ssl_clear"`
	UprobeSslFree           *ebpf.ProgramSpec `ebpf:"uprobe_ssl_free"`
	UprobeSslRead           *ebpf.ProgramSpec `ebpf:"uprobe_ssl_read"`
	UprobeSslReadEx         *ebpf.ProgramSpec `ebpf:"uprobe_ssl_read_ex"`
	UprobeSslSetAcceptState *ebpf.ProgramSpec `ebpf:"uprobe_ssl_set_accept_state"`
	UprobeSslSetFd          *ebpf.ProgramSpec `ebpf:"uprobe_ssl_set_fd"`
	UprobeSslSetRfd         *ebpf.ProgramSpec `ebpf:"uprobe_ssl_set_rfd"`
	UprobeSslSetWfd         *ebpf.ProgramSpec `ebpf:"uprobe_ssl_set_wfd"`
	UprobeSslShutdown       *ebpf.ProgramSpec `ebpf:"uprobe_ssl_shutdown"`
	UprobeSslWrite          *ebpf.ProgramSpec `ebpf:"uprobe_ssl_write"`
	UprobeSslWriteEx        *ebpf.ProgramSpec `ebpf:"uprobe_ssl_write_ex"`
	UretprobeSslRead        *ebpf.ProgramSpec `ebpf:"uretprobe_ssl_read"`
	UretprobeSslReadEx      *ebpf.ProgramSpec `ebpf:"uretprobe_ssl_read_ex"`
	UretprobeSslSetFd       *ebpf.ProgramSpec `ebpf:"uretprobe_ssl_set_fd"`
	UretprobeSslSetRfd      *ebpf.ProgramSpec `ebpf:"uretprobe_ssl_set_rfd"`
	UretprobeSslSetWfd      *ebpf.ProgramSpec `ebpf:"uretprobe_ssl_set_wfd"`
	UretprobeSslWrite       *ebpf.ProgramSpec `ebpf:"uretprobe_ssl_write"`
	UretprobeSslWriteEx     *ebpf.ProgramSpec `ebpf:"uretprobe_ssl_write_ex"`
}

// TlsTraceLegacyMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TlsTraceLegacyMapSpecs struct {
	Events        *ebpf.MapSpec `ebpf:"events"`
	ScratchHeap   *ebpf.MapSpec `ebpf:"scratch_heap"`
	TlsConfigMap  *ebpf.MapSpec `ebpf:"tls_config_map"`
	TlsFdArgsMap  *ebpf.MapSpec `ebpf:"tls_fd_args_map"`
	TlsFlowMap    *ebpf.MapSpec `ebpf:"tls_flow_map"`
	TlsRwArgsMap  *ebpf.MapSpec `ebpf:"tls_rw_args_map"`
	TlsSessionMap *ebpf.MapSpec `ebpf:"tls_session_map"`
}

// TlsTraceLegacyVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TlsTraceLegacyVariableSpecs struct {
}

// TlsTraceLegacyObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadTlsTraceLegacyObjects or ebpf.CollectionSpec.LoadAndAssign.
type TlsTraceLegacyObjects struct {
	TlsTraceLegacyPrograms
	TlsTraceLegacyMaps
	TlsTraceLegacyVariables
}

func (o *TlsTraceLegacyObjects) Close() error {
	return _TlsTraceLegacyClose(
		&o.TlsTraceLegacyPrograms,
		&o.TlsTraceLegacyMaps,
	)
}

// TlsTraceLegacyMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadTlsTraceLegacyObjects or ebpf.CollectionSpec.LoadAndAssign.
type TlsTraceLegacyMaps struct {
	Events        *ebpf.Map `ebpf:"events"`
	ScratchHeap   *ebpf.Map `ebpf:"scratch_heap"`
	TlsConfigMap  *ebpf.Map `ebpf:"tls_config_map"`
	TlsFdArgsMap  *ebpf.Map `ebpf:"tls_fd_args_map"`
	TlsFlowMap    *ebpf.Map `ebpf:"tls_flow_map"`
	TlsRwArgsMap  *ebpf.Map `ebpf:"tls_rw_args_map"`
	TlsSessionMap *ebpf.Map `ebpf:"tls_session_map"`
}

func (m *TlsTraceLegacyMaps) Close() error {
	return _TlsTraceLegacyClose(
		m.Events,
		m.ScratchHeap,
		m.TlsConfigMap,
		m.TlsFdArgsMap,
		m.TlsFlowMap,
		m.TlsRwArgsMap,
		m.TlsSessionMap,
	)
}

// TlsTraceLegacyVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadTlsTraceLegacyObjects or ebpf.CollectionSpec.LoadAndAssign.
type TlsTraceLegacyVariables struct {
}

// TlsTraceLegacyPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadTlsTraceLegacyObjects or ebpf.CollectionSpec.LoadAndAssign.
type TlsTraceLegacyPrograms struct {
	UprobeSslClear          *ebpf.Program `ebpf:"uprobe_ssl_clear"`
	UprobeSslFree           *ebpf.Program `ebpf:"uprobe_ssl_free"`
	UprobeSslRead           *ebpf.Program `ebpf:"uprobe_ssl_read"`
	UprobeSslReadEx         *ebpf.Program `ebpf:"uprobe_ssl_read_ex"`
	UprobeSslSetAcceptState *ebpf.Program `ebpf:"uprobe_ssl_set_accept_state"`
	UprobeSslSetFd          *ebpf.Program `ebpf:"uprobe_ssl_set_fd"`
	UprobeSslSetRfd         *ebpf.Program `ebpf:"uprobe_ssl_set_rfd"`
	UprobeSslSetWfd         *ebpf.Program `ebpf:"uprobe_ssl_set_wfd"`
	UprobeSslShutdown       *ebpf.Program `ebpf:"uprobe_ssl_shutdown"`
	UprobeSslWrite          *ebpf.Program `ebpf:"uprobe_ssl_write"`
	UprobeSslWriteEx        *ebpf.Program `ebpf:"uprobe_ssl_write_ex"`
	UretprobeSslRead        *ebpf.Program `ebpf:"uretprobe_ssl_read"`
	UretprobeSslReadEx      *ebpf.Program `ebpf:"uretprobe_ssl_read_ex"`
	UretprobeSslSetFd       *ebpf.Program `ebpf:"uretprobe_ssl_set_fd"`
	UretprobeSslSetRfd      *ebpf.Program `ebpf:"uretprobe_ssl_set_rfd"`
	UretprobeSslSetWfd      *ebpf.Program `ebpf:"uretprobe_ssl_set_wfd"`
	UretprobeSslWrite       *ebpf.Program `ebpf:"uretprobe_ssl_write"`
	UretprobeSslWriteEx     *ebpf.Program `ebpf:"uretprobe_ssl_write_ex"`
}

func (p *TlsTraceLegacyPrograms) Close() error {
	return _TlsTraceLegacyClose(
		p.UprobeSslClear,
		p.UprobeSslFree,
		p.UprobeSslRead,
		p.UprobeSslReadEx,
		p.UprobeSslSetAcceptState,
		p.UprobeSslSetFd,
		p.UprobeSslSetRfd,
		p.UprobeSslSetWfd,
		p.UprobeSslShutdown,
		p.UprobeSslWrite,
		p.UprobeSslWriteEx,
		p.UretprobeSslRead,
		p.UretprobeSslReadEx,
		p.UretprobeSslSetFd,
		p.UretprobeSslSetRfd,
		p.UretprobeSslSetWfd,
		p.UretprobeSslWrite,
		p.UretprobeSslWriteEx,
	)
}

func _TlsTraceLegacyClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed tlstracelegacy_x86_bpfel.o
var _TlsTraceLegacyBytes []byte
