// Code generated by bpf2go; DO NOT EDIT.
//go:build arm64 && linux

package bpfgen

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// LoadTlsTrace returns the embedded CollectionSpec for TlsTrace.
func LoadTlsTrace() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TlsTraceBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load TlsTrace: %w", err)
	}

	return spec, err
}

// LoadTlsTraceObjects loads TlsTrace and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*TlsTraceObjects
//	*TlsTracePrograms
//	*TlsTraceMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadTlsTraceObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadTlsTrace()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// TlsTraceSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TlsTraceSpecs struct {
	TlsTraceProgramSpecs
	TlsTraceMapSpecs
	TlsTraceVariableSpecs
}

// TlsTraceProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TlsTraceProgramSpecs struct {
	UprobeSslFree       *ebpf.ProgramSpec `ebpf:"uprobe_ssl_free"`
	UprobeSslRead       *ebpf.ProgramSpec `ebpf:"uprobe_ssl_read"`
	UprobeSslReadEx     *ebpf.ProgramSpec `ebpf:"uprobe_ssl_read_ex"`
	UprobeSslSetFd      *ebpf.ProgramSpec `ebpf:"uprobe_ssl_set_fd"`
	UprobeSslSetRfd     *ebpf.ProgramSpec `ebpf:"uprobe_ssl_set_rfd"`
	UprobeSslSetWfd     *ebpf.ProgramSpec `ebpf:"uprobe_ssl_set_wfd"`
	UprobeSslShutdown   *ebpf.ProgramSpec `ebpf:"uprobe_ssl_shutdown"`
	UprobeSslWrite      *ebpf.ProgramSpec `ebpf:"uprobe_ssl_write"`
	UprobeSslWriteEx    *ebpf.ProgramSpec `ebpf:"uprobe_ssl_write_ex"`
	UretprobeSslRead    *ebpf.ProgramSpec `ebpf:"uretprobe_ssl_read"`
	UretprobeSslReadEx  *ebpf.ProgramSpec `ebpf:"uretprobe_ssl_read_ex"`
	UretprobeSslSetFd   *ebpf.ProgramSpec `ebpf:"uretprobe_ssl_set_fd"`
	UretprobeSslSetRfd  *ebpf.ProgramSpec `ebpf:"uretprobe_ssl_set_rfd"`
	UretprobeSslSetWfd  *ebpf.ProgramSpec `ebpf:"uretprobe_ssl_set_wfd"`
	UretprobeSslWrite   *ebpf.ProgramSpec `ebpf:"uretprobe_ssl_write"`
	UretprobeSslWriteEx *ebpf.ProgramSpec `ebpf:"uretprobe_ssl_write_ex"`
}

// TlsTraceMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TlsTraceMapSpecs struct {
	Events       *ebpf.MapSpec `ebpf:"events"`
	ScratchHeap  *ebpf.MapSpec `ebpf:"scratch_heap"`
	TlsConfigMap *ebpf.MapSpec `ebpf:"tls_config_map"`
	TlsFdArgsMap *ebpf.MapSpec `ebpf:"tls_fd_args_map"`
	TlsFdMap     *ebpf.MapSpec `ebpf:"tls_fd_map"`
	TlsFlowMap   *ebpf.MapSpec `ebpf:"tls_flow_map"`
	TlsRwArgsMap *ebpf.MapSpec `ebpf:"tls_rw_args_map"`
}

// TlsTraceVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TlsTraceVariableSpecs struct {
}

// TlsTraceObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadTlsTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type TlsTraceObjects struct {
	TlsTracePrograms
	TlsTraceMaps
	TlsTraceVariables
}

func (o *TlsTraceObjects) Close() error {
	return _TlsTraceClose(
		&o.TlsTracePrograms,
		&o.TlsTraceMaps,
	)
}

// TlsTraceMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadTlsTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type TlsTraceMaps struct {
	Events       *ebpf.Map `ebpf:"events"`
	ScratchHeap  *ebpf.Map `ebpf:"scratch_heap"`
	TlsConfigMap *ebpf.Map `ebpf:"tls_config_map"`
	TlsFdArgsMap *ebpf.Map `ebpf:"tls_fd_args_map"`
	TlsFdMap     *ebpf.Map `ebpf:"tls_fd_map"`
	TlsFlowMap   *ebpf.Map `ebpf:"tls_flow_map"`
	TlsRwArgsMap *ebpf.Map `ebpf:"tls_rw_args_map"`
}

func (m *TlsTraceMaps) Close() error {
	return _TlsTraceClose(
		m.Events,
		m.ScratchHeap,
		m.TlsConfigMap,
		m.TlsFdArgsMap,
		m.TlsFdMap,
		m.TlsFlowMap,
		m.TlsRwArgsMap,
	)
}

// TlsTraceVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadTlsTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type TlsTraceVariables struct {
}

// TlsTracePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadTlsTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type TlsTracePrograms struct {
	UprobeSslFree       *ebpf.Program `ebpf:"uprobe_ssl_free"`
	UprobeSslRead       *ebpf.Program `ebpf:"uprobe_ssl_read"`
	UprobeSslReadEx     *ebpf.Program `ebpf:"uprobe_ssl_read_ex"`
	UprobeSslSetFd      *ebpf.Program `ebpf:"uprobe_ssl_set_fd"`
	UprobeSslSetRfd     *ebpf.Program `ebpf:"uprobe_ssl_set_rfd"`
	UprobeSslSetWfd     *ebpf.Program `ebpf:"uprobe_ssl_set_wfd"`
	UprobeSslShutdown   *ebpf.Program `ebpf:"uprobe_ssl_shutdown"`
	UprobeSslWrite      *ebpf.Program `ebpf:"uprobe_ssl_write"`
	UprobeSslWriteEx    *ebpf.Program `ebpf:"uprobe_ssl_write_ex"`
	UretprobeSslRead    *ebpf.Program `ebpf:"uretprobe_ssl_read"`
	UretprobeSslReadEx  *ebpf.Program `ebpf:"uretprobe_ssl_read_ex"`
	UretprobeSslSetFd   *ebpf.Program `ebpf:"uretprobe_ssl_set_fd"`
	UretprobeSslSetRfd  *ebpf.Program `ebpf:"uretprobe_ssl_set_rfd"`
	UretprobeSslSetWfd  *ebpf.Program `ebpf:"uretprobe_ssl_set_wfd"`
	UretprobeSslWrite   *ebpf.Program `ebpf:"uretprobe_ssl_write"`
	UretprobeSslWriteEx *ebpf.Program `ebpf:"uretprobe_ssl_write_ex"`
}

func (p *TlsTracePrograms) Close() error {
	return _TlsTraceClose(
		p.UprobeSslFree,
		p.UprobeSslRead,
		p.UprobeSslReadEx,
		p.UprobeSslSetFd,
		p.UprobeSslSetRfd,
		p.UprobeSslSetWfd,
		p.UprobeSslShutdown,
		p.UprobeSslWrite,
		p.UprobeSslWriteEx,
		p.UretprobeSslRead,
		p.UretprobeSslReadEx,
		p.UretprobeSslSetFd,
		p.UretprobeSslSetRfd,
		p.UretprobeSslSetWfd,
		p.UretprobeSslWrite,
		p.UretprobeSslWriteEx,
	)
}

func _TlsTraceClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed tlstrace_arm64_bpfel.o
var _TlsTraceBytes []byte
